// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7AjDRndcWNas18ROPskStUjamz19HYlI',
    appId: '1:1026070013724:web:27f31639a652f28281fcd9',
    messagingSenderId: '1026070013724',
    projectId: 'nativeartist-5bd60',
    authDomain: 'nativeartist-5bd60.firebaseapp.com',
    storageBucket: 'nativeartist-5bd60.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAULsT_igso6P7eZ3Iemxwm6eMXP_j29ko',
    appId: '1:1026070013724:android:05d17d3f76e0999181fcd9',
    messagingSenderId: '1026070013724',
    projectId: 'nativeartist-5bd60',
    storageBucket: 'nativeartist-5bd60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhWuwtZ5tfrLEdRdw5h6jY1Dyj716cwAk',
    appId: '1:1026070013724:ios:c3236a751b540a3981fcd9',
    messagingSenderId: '1026070013724',
    projectId: 'nativeartist-5bd60',
    storageBucket: 'nativeartist-5bd60.appspot.com',
    androidClientId: '1026070013724-9bnpbsrgibl6dg77c2ie1u913ok3ku36.apps.googleusercontent.com',
    iosClientId: '1026070013724-2vthtd65d3ks3vggru8e29ikpn6h2j37.apps.googleusercontent.com',
    iosBundleId: 'com.example.kalakaarAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhWuwtZ5tfrLEdRdw5h6jY1Dyj716cwAk',
    appId: '1:1026070013724:ios:c3236a751b540a3981fcd9',
    messagingSenderId: '1026070013724',
    projectId: 'nativeartist-5bd60',
    storageBucket: 'nativeartist-5bd60.appspot.com',
    androidClientId: '1026070013724-9bnpbsrgibl6dg77c2ie1u913ok3ku36.apps.googleusercontent.com',
    iosClientId: '1026070013724-2vthtd65d3ks3vggru8e29ikpn6h2j37.apps.googleusercontent.com',
    iosBundleId: 'com.example.kalakaarAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoONZ6j0Md6Lw1SOkQ7brpbmyiprGL4uY',
    appId: '1:1026070013724:web:105e274131e0ddf781fcd9',
    messagingSenderId: '1026070013724',
    projectId: 'nativeartist-5bd60',
    authDomain: 'nativeartist-5bd60.firebaseapp.com',
    storageBucket: 'nativeartist-5bd60.appspot.com',
  );

}