// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs2X7sYwaGvjYVeTDvTaQUYZzWelIYKts',
    appId: '1:423168411417:web:67f75402f4361034ede788',
    messagingSenderId: '423168411417',
    projectId: 'kalakaar-e2fa1',
    authDomain: 'kalakaar-e2fa1.firebaseapp.com',
    storageBucket: 'kalakaar-e2fa1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANLm2tc2qdniBzYEpLNzNR-YLx0yWe1V0',
    appId: '1:423168411417:android:ae478d51574891f1ede788',
    messagingSenderId: '423168411417',
    projectId: 'kalakaar-e2fa1',
    storageBucket: 'kalakaar-e2fa1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNumn76zgDEhtyAyI9F1JrTrqrUePd06M',
    appId: '1:423168411417:ios:49d969ff6de07dacede788',
    messagingSenderId: '423168411417',
    projectId: 'kalakaar-e2fa1',
    storageBucket: 'kalakaar-e2fa1.firebasestorage.app',
    iosClientId: '423168411417-eurgic04j74g63p0e3sq605j3v9frf93.apps.googleusercontent.com',
    iosBundleId: 'com.example.kalakaarAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNumn76zgDEhtyAyI9F1JrTrqrUePd06M',
    appId: '1:423168411417:ios:49d969ff6de07dacede788',
    messagingSenderId: '423168411417',
    projectId: 'kalakaar-e2fa1',
    storageBucket: 'kalakaar-e2fa1.firebasestorage.app',
    iosClientId: '423168411417-eurgic04j74g63p0e3sq605j3v9frf93.apps.googleusercontent.com',
    iosBundleId: 'com.example.kalakaarAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDs2X7sYwaGvjYVeTDvTaQUYZzWelIYKts',
    appId: '1:423168411417:web:8b599eff6e17b6fcede788',
    messagingSenderId: '423168411417',
    projectId: 'kalakaar-e2fa1',
    authDomain: 'kalakaar-e2fa1.firebaseapp.com',
    storageBucket: 'kalakaar-e2fa1.firebasestorage.app',
  );
}
